stages:
  preprocess:
    cmd: python notebooks/02_data_preprocessing.py
    deps:
      - notebooks/02_data_preprocessing.py
      - data/processed/student_entry_performance_eda.csv
    params:
      - preprocessing.test_size
      - preprocessing.random_state
    outs:
      - data/processed/student_performance_cleaned.csv:
          persist: true
      - data/processed/student_performance_preprocessed.csv:
          persist: true
      - data/processed/student_performance_train.csv:
          persist: true
      - data/processed/student_performance_test.csv:
          persist: true
      - data/processed/feature_names.txt:
          persist: true
      - reports/figures:
          persist: true
